### PR TITLE
Proposals: Convert to jekyll

### PR DESCRIPTION
**Pull request by rtorr**
So almost a month went by for https://github.com/meltmedia/whyaz/issues/30 so I took a stab at an idea. No harm or obligations if this pull request is denied.

**Main benefits:**

* Automated deploys every time you merge into gh-pages, in fact, it can become the master branch
* You don't need to build locally and then push, github understands jekyll because they maintain that project.
* Documentation
* Wide use around the community

Work to do: 

* **CNAME**: Change the `CNAME` config where ever you are hosting the domain https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

* **Stylus to SASS**: Unfortunately gh-pages does not support the stylus gem, but we do have native support for sass

cc @kennedyj @ncrohn @jacobheun @lynnandtonic

### CODE REVIEW

**Comment by lynnandtonic** [comment]
Thanks, Richard. I'm going to take a look and think about things.

**Comment by lynnandtonic** [comment]
Does Jekyll not have Jade support?

**Comment by rtorr** [comment]
@lynnandtonic Jekyll itself does have plugins for both jade and stylus. However, gh-pages unfortunatly only has support for these plugins https://help.github.com/articles/using-jekyll-plugins-with-github-pages/

**Comment by rtorr** [comment]
Just to reiterate what I told lynn in private chat:

A couple years ago now, I switched over the [http://vim.rtorr.com/](vim-cheat-sheet) project from a node/stylus/jade build system to using jekyll. Although I like the prior tools more, the benefit and ease of maintenance of jekyll project made it worth it to me.

**Comment by lynnandtonic** [comment]
I appreciate the work here Richard and it's brought up a lot of questions for me that are valuable.

In the end, I would rather not move from *both* Jade and Stylus.

Also, with me as primary maintainer and "asker of favors" I'd like to stick with Node. All the people I would ask for help are writing a lot of Node and not a lot of Ruby. It's more familiar for me too.

Thank you! <3

**Comment by rtorr** [comment]
Makes sense!

**Pull request closed without merging**
